# Generated by Django 3.2.17 on 2023-02-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aldryn_news", "0005_news_canonical_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="ordering",
            field=models.IntegerField(default=0, verbose_name="Ordering"),
        ),
    ]
