# Generated by Django 3.2.19 on 2023-05-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('aldryn_news', '0006_tags_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='meta_description',
            field=models.CharField(default='', max_length=255, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='news',
            name='meta_title',
            field=models.CharField(default='', max_length=100, verbose_name='Meta Title'),
        ),
    ]
